file:
  pattern: "*.xml"
  
local:
  workingdir: "{add-here-your-working-directory}"
  input-stream: "in-stream/"
  input-mimetype: "in-mimetype/"
  output: "out/"
  reconnection.frequency: "2500"
  reconnection.attempts: "2"  
